### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by stuartc** [OpenFn/language-http#13]
Before we replace `request` with our own `http...` functions from `language-common` we need to make sure we have tests for the current behaviour.

In this branch [here](https://github.com/OpenFn/language-http/tree/better-test) is some of the work already done, but needs to be complete.

The goal is to finish the pending tests, add more for the other HTTP verbs - and then remove any overlap with the original tests.
Once that's merged we can move to get `language-common`'s new functions in there...

**Comment by taylordowns2000** [comment]
@chaiwa-berian , the first part of this (finishing up the pending tests) looks perfect :+1: 

@stuartc , how would you like us to proceed? given that this is likely going to be backwards compatible, but doesn't _have_ to be (given version locking on platform) could we move forward with the re-implementation in #14 or should we add tests for other verbs as well.

**Comment by chaiwa-berian** [comment]
@stuartc and @taylordowns2000 Also, not too sure how this will play out. Considering the operation signatures exposed to the users in `language-http` maybe slightly different from those exposed and/or supported by the corresponding operations in language-common/axios. For example:

1. Method Signatures
- In `language-http`, the `post` operation looks like below:

     _`post(path, params, callback)`_

- While in `language-common`, the `post` operation looks like below:

   _`post(params,callback)`_

- What would you recommend? Should we re-implement the `http operations` in `language-common` to match the signatures expected by `language-http` `methods`?

2. Request Params/Config Object
- `language-http` uses slightly different property names in the config object to those used in the request config for language-common/axios. How would the destructing or mapping of those properties work?
- For example:
  - In `language-http`, the config object can be sent as `{body: {d:1,e:3}, authentication: {username: 'user', password: 'pass'}}`
  - While in `language-common`, the equivalent config would be `{data: {d:1,e:3},auth:{username: 'user', password: 'pass'}}`
  - It seems we may need to adapt `language-common` for `language-http` users while providing newer interface to subsequent jobs built on `language-common`. Or should we just align the **new http operations**(now in language-common) with `language-http` signatures for a much smoother transition and backward compatibility?

**Comment by stuartc** [comment]
@chaiwa-berian Looking good!

So regarding the testing, it's really important we do tests for everything - so PUT, PATCH etc all of the verbs need to be tested. 
Especially the cookie one (let me know if you want me to figure out why it's not passing).

Thats where this issue ends - just tests.

I'll address the use of `language-common.http` in #14.

**Comment by taylordowns2000** [comment]
Sorry, forgot to link this commit to the issue: https://github.com/OpenFn/language-http/commit/52f30b01800745557f499f70e4fcd2d50347b1a1 Cookies are now passing. Chaiwa, please keep on going with the rest of the verbs.

@stuartc , also, I'm shifting all `Makefile` babel entries to use the babel version from node_modules: (`./node_modules/.bin/babel $< -o $@`). Before, it was relying on whatever babel was around (which was globally installed in many cases).

**Comment by taylordowns2000** [comment]
These are good examples of two edge cases we need to add tests for: `formData` and `successCodes`.

1. https://github.com/OpenFn/dial-pilot/search?q=formData
2. https://github.com/OpenFn/dial-pilot/search?q=successCodes

In `language-http`, it's possible to specify the response codes that you want to count as "successes" in order to continue on with your job... in this case, the client has specified that they should treat a `302` as a kind of success, or at least that they don't want to throw a Javascript error when they hit a `302`.

**Comment by chaiwa-berian** [comment]
## Tests Checklist
- [x] execute
- [x] get
- [x] post
- [ ] put
- [ ] patch
- [ ] del
