### ISSUE TITLE
Replace request dependency with language-common.http

### ISSUE THREAD

**Issue by stuartc** [OpenFn/language-http#14]
In an effort to replace the `request` library that we use, we would like to use our new shiny `http` wrappers that come with `language-common`.

But before that can happen we need to address #13

**Comment by stuartc** [comment]
Re: feedback from #13 .

> 1. Method Signatures
> - In `language-http`, the `post` operation looks like below:
> 
>      _`post(path, params, callback)`_
> 
> - While in `language-common`, the `post` operation looks like below:
> 
>    _`post(params,callback)`_
> 
> - What would you recommend? Should we re-implement the `http operations` in `language-common` to match the signatures expected by `language-http` `methods`?

I think we should maintain the same signatures, so if #13 has solid tests
we can lean on - we should be able to remove `request` from underneath and
still have passing tests.

> 2. Request Params/Config Object
> - `language-http` uses slightly different property names in the config object to those used in the request config for language-common/axios. How would the destructing or mapping of those properties work?
> - For example:
>   - In `language-http`, the config object can be sent as `{body: {d:1,e:3}, authentication: {username: 'user', password: 'pass'}}`
>   - While in `language-common`, the equivalent config would be `{data: {d:1,e:3},auth:{username: 'user', password: 'pass'}}`
>   - It seems we may need to adapt `language-common` for `language-http` users while providing newer interface to subsequent jobs built on `language-common`. Or should we just align the **new http operations**(now in language-common) with `language-http` signatures for a much smoother transition and backward compatibility?

So for this, I think the same applies - conform the current `language-http` 
arguments to work with `language-common.http`.

I suggest creating a new object that provides the keys `request` expects.

```javascript
const { authentication, body, ...rest } = params;
// Coerce/rename/add items that need to be flipped around.
// This is where enabling cookies, redirect following, authentication would take place
const requestParams = expandReference({ url, auth: authentication, ...rest });

return http.post(requestParams).then(
	response => {
		const nextState = composeNextState(state, response);
		if (callback) return callback(nextState);
		return nextState;
	}
);
```

On thing that is important to pay attention to, and this may need to be addressed
in #13: how do users post different kinds of data? I see `language-http` currently
has `body` and `formData` keys for it's arguments... not sure `formData` is tested?

**Comment by chaiwa-berian** [comment]
@stuartc Looks good. Or would **overriding** the methods make the migration process much easier? So that would mean having two `post` operations, for example, one compatible with `language-http` style and the other as  proposed in the new setup:
- `_post(url,params,cb)_` - For backward compatibility, with a deprecation message annotated
- `_post(params_` -  New way of doing things going forward.

**Comment by stuartc** [comment]
@chaiwa-berian I think that's a good idea, but that feel that's our of scope for this issue.

The intent is to remove `request`. Since it's been deprecated since Feb last year.
I understand the amount of work required in ensuring backwards compatibility and I'm
hoping the test suite work in #13 will make this work much simpler.

I think we should try and avoid creating a 'stop gap' solution - we're removing `request` to protect people
from any security vulnerabilities that won't be fixed in the library.
I do agree with you that getting customers to use a newer interface is also important - like using `.then` instead of callbacks etc.

@taylordowns2000 your thoughts?

**Comment by taylordowns2000** [comment]
Agreed. After fixing up the tests, let's replace `request` with `language-common.http` entirely under the hood if we can, and then decide about new signatures/overrides-for-migration, etc. later.

**Comment by chaiwa-berian** [comment]
@stuartc and @taylordowns2000 I have a few **questions** and  **blockers** regarding this issue as below:

1. @stuartc  I am not too sure how `language-http` should return state: I noticed the use of [tryJSON](https://github.com/OpenFn/language-http/blob/329b2b481e62886e7da890bc72af7adb176033c9/src/Utils.js#L34-L40) and how sometimes data is saved in `state.data.body`? Would you clarify on how this works. I am [intercepting every response](https://github.com/OpenFn/language-http/blob/329b2b481e62886e7da890bc72af7adb176033c9/src/Adaptor.js#L78) with `tryJSON` but I had to change the way some of the tests were looking for data, so they can now look at `state.data.body` and sometimes at `state.data`. Not knowing how the existing expressions are handling this, makes it a **blocker** for deployment of the new version unless thoroughly tested, this may break a lot of existing jobs. So I need your help here, to help clarify and look at my code. See [example how I return data](https://github.com/OpenFn/language-http/blob/329b2b481e62886e7da890bc72af7adb176033c9/src/Adaptor.js#L78-L87).

2. Sending data as `formData` is failing with error `TypeError: next is not a function`. I am using the `form-data` package to prepare data as `formData` before sending it to `axios`. See code [here](https://github.com/OpenFn/language-http/blob/329b2b481e62886e7da890bc72af7adb176033c9/src/Utils.js#L55-L66). Help here would be appreciated.

3. `expandReferences` in `language-common` is giving challenges expanding/parsing objects such as `{}` and `[]`. One of the tests is failing on this. Help on this is also needed.

4. I am currently on this [branch](https://github.com/OpenFn/language-common/tree/export_axios) for `language-common` so any changes to `language-common`, related to this issue, kindly push them there.

**Comment by taylordowns2000** [comment]
this is breaking my brain. all looks great, @chaiwa-berian , but i'm struggling with the same multipart `formData` thing you were. my guess it is has to do not with axios, per se, but with how we wrap it up in common. will keep you posted.
