### ISSUE TITLE
Change to not log response body by default

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-http#7]
Currently the response `body` is logged by default (example: [see L103 here](https://www.openfn.org/projects/1671/runs/9341807)). 

Can we please change this to give users the control about if/ how they log responses to requests. I know this for sure impacts `GET` and `POST` requests, but maybe all methods.

**Comment by taylordowns2000** [comment]
Closed in https://github.com/OpenFn/language-http/releases/tag/v2.4.9
